
services:
  database:
    image: postgres:16
    container_name: skyscrape_db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - skyscrape_db_data:/var/lib/postgresql/data

volumes:
  skyscrape_db_data:
